# -*- coding: utf-8 -*-
"""Middleware.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASDLvNLDnppTxg_WTZNLspJrrJlSQDd1
"""

## Part 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install fastapi uvicorn[standard] structlog tenacity pybreaker \
#              prometheus-client prometheus-fastapi-instrumentator \
#              httpx pyngrok nest-asyncio

import nest_asyncio
nest_asyncio.apply()  # Allow asyncio inside Colab's event loop
print('✅ Dependencies installed and asyncio patched')

"""

!pip install fastapi uvicorn[standard] structlog tenacity pybreaker \
             prometheus-client prometheus-fastapi-instrumentator \
             httpx pyngrok nest-asyncio

import nest_asyncio
nest_asyncio.apply()  # Allow asyncio inside Colab's event loop
print('✅ Dependencies installed and asyncio patched')

import structlog, logging, uuid, time
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Configure structlog to output clean JSON
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.PrintLoggerFactory(),
)

log = structlog.get_logger()

app = FastAPI(title='EY Payment API', version='1.0.0')

@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))
    correlation_id_var.set(correlation_id)
    start = time.perf_counter()

    log.info('request.started',
             path=request.url.path,
             method=request.method,
             correlation_id=correlation_id)

    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

    log.info('request.completed',
             path=request.url.path,
             status=response.status_code,
             latency_ms=elapsed_ms,
             correlation_id=correlation_id)

    response.headers['X-Correlation-Id'] = correlation_id
    return response

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    log.info('payment.received', amount=body.get('amount'), currency=body.get('currency', 'GBP'))
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', **body}

print('✅ Logging middleware and routes defined')

from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from prometheus_fastapi_instrumentator import Instrumentator
from fastapi.responses import Response

# Custom business metric: track payment amounts by currency
PAYMENT_AMOUNT = Histogram(
    'payment_amount_gbp', 'Payment amount in GBP',
    buckets=[10, 50, 100, 500, 1000, 5000, 10000]
)

ERROR_COUNT = Counter(
    'payment_errors_total', 'Total payment processing errors',
    ['error_type']
)

# Auto-instrument all HTTP routes (latency, status codes, method)
Instrumentator().instrument(app).expose(app)

print('✅ Prometheus metrics instrumented')
print('   → /metrics endpoint is now available')
print('   → Tracking: request_count, request_latency, payment_amount')

import random
import asyncio
from tenacity import (
    retry, stop_after_attempt, wait_exponential,
    retry_if_exception_type, before_sleep_log
)

# Simulate a flaky downstream fraud-check service
call_count = 0

async def flaky_fraud_check(payload: dict) -> dict:
    global call_count
    call_count += 1
    # Fail the first 2 attempts, succeed on 3rd
    if call_count < 3:
        print(f'  ⚠️  Attempt {call_count}: fraud API timeout (simulated)')
        raise ConnectionError(f'Fraud API timeout on attempt {call_count}')
    print(f'  ✅ Attempt {call_count}: fraud check passed')
    return {'fraud_score': 0.02, 'decision': 'approved'}


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=1, min=0.1, max=2),  # seconds (small for demo)
    retry=retry_if_exception_type((ConnectionError, TimeoutError)),
    reraise=True
)
async def call_fraud_api_with_retry(payload: dict) -> dict:
    return await flaky_fraud_check(payload)


# Test it
print('🔄 Testing retry logic...')
result = asyncio.run(
    call_fraud_api_with_retry({'amount': 1500, 'currency': 'GBP'})
)
print(f'\n📦 Final result: {result}')

import pybreaker

class LoggingListener(pybreaker.CircuitBreakerListener):
    def state_change(self, cb, old_state, new_state):
        log.warning('circuit_breaker.state_change',
                    breaker=cb.name,
                    old=str(old_state),
                    new=str(new_state))

fraud_breaker = pybreaker.CircuitBreaker(
    fail_max=3,
    reset_timeout=30,
    listeners=[LoggingListener()],
    name='fraud-api'
)

def check_fraud_cb(payload: dict) -> dict:
    """Wrapped by circuit breaker — raises CircuitBreakerError when OPEN."""
    # Simulate always-failing service for demo
    raise ConnectionError('Fraud service down')

def safe_fraud_check(payload: dict) -> dict:
    """Call fraud API with circuit breaker; return fallback if circuit is OPEN."""
    try:
        return fraud_breaker.call(check_fraud_cb, payload)
    except pybreaker.CircuitBreakerError:
        print('🔴 Circuit OPEN — returning safe fallback (manual review)')
        return {'fraud_score': None, 'decision': 'manual_review', 'circuit': 'open'}
    except Exception as e:
        return {'fraud_score': None, 'decision': 'error', 'reason': str(e)}

print('📊 Simulating calls to a failing fraud service...')
for i in range(6):
    result = safe_fraud_check({'amount': 200 * (i + 1)})
    print(f'  Call {i+1}: {result} | Circuit state: {fraud_breaker.current_state}')

NGROK_TOKEN = 'YOUR_NGROK_TOKEN_HERE'  # ← REPLACE THIS WITH YOUR ACTUAL NGROK TOKEN

import threading, uvicorn
from pyngrok import ngrok, conf

conf.get_default().auth_token = NGROK_TOKEN

def run_server():
    uvicorn.run(app, host='0.0.0.0', port=8000, log_level='warning')

thread = threading.Thread(target=run_server, daemon=True)
thread.start()

import time; time.sleep(2)
tunnel = ngrok.connect(8000)
public_url = tunnel.public_url

print(f'🌐 Public URL: {public_url}')
print(f'   Health:   {public_url}/health/ready')
print(f'   Metrics:  {public_url}/metrics')
print(f'   Docs:     {public_url}/docs')

# Quick smoke tests using httpx
import httpx, json

BASE = public_url  # set in the cell above

with httpx.Client() as client:
    # 1 — Health check
    r = client.get(f'{BASE}/health/ready')
    print('Health:', r.json())

    # 2 — POST a payment (watch structured logs above)
    r = client.post(f'{BASE}/payments',
                    json={'amount': 1500, 'currency': 'GBP', 'account': 'ACC-42'},
                    headers={'X-Correlation-Id': 'demo-corr-001'})
    print('Payment:', r.json())
    print('Returned correlation ID:', r.headers.get('X-Correlation-Id'))

    # 3 — Peek at first 500 chars of /metrics
    r = client.get(f'{BASE}/metrics')
    print('\nMetrics (first 500 chars):')
    print(r.text[:500])

"""🔥 Extension Tasks"""

### Extension A — Rate-Limiting Middleware *(Medium)*
# Add a sliding-window rate limiter (e.g., 100 req/min per client IP) using an in-memory dictionary.
# - Return `429 Too Many Requests` with a `Retry-After` header when the limit is exceeded
# - Track limit hits as a Prometheus `Counter`

from prometheus_client import Counter

RATE_LIMIT_HITS = Counter(
    "rate_limit_hits_total",
    "Total requests rejected due to rate limiting"
)

from collections import defaultdict
from datetime import datetime, timedelta

REQUEST_LOG = defaultdict(list)

RATE_LIMIT = 100
WINDOW_SECONDS = 60

from fastapi.responses import JSONResponse

@app.middleware("http")
async def rate_limit_middleware(request: Request, call_next):

    client_ip = request.client.host
    now = datetime.utcnow()

    REQUEST_LOG[client_ip] = [
        ts for ts in REQUEST_LOG[client_ip]
        if now - ts < timedelta(seconds=WINDOW_SECONDS)
    ]

    if len(REQUEST_LOG[client_ip]) >= RATE_LIMIT:

        RATE_LIMIT_HITS.inc()

        return JSONResponse(
            status_code=429,
            headers={"Retry-After": "60"},
            content={
                "error": "Rate limit exceeded"
            }
        )

    REQUEST_LOG[client_ip].append(now)

    return await call_next(request)

### Extension B — Correlation ID Propagation *(Medium)*
# The current middleware assigns a correlation ID but does NOT forward it to outbound `httpx` calls.
# - Add a `contextvars.ContextVar` to store the correlation ID per request
# - Write a custom `httpx.Auth` or event hook that injects `X-Correlation-Id` into every outbound call
# - Verify it appears in mock downstream requests

import contextvars
correlation_id_var = contextvars.ContextVar(
    "correlation_id",
    default=None
)

correlation_id = correlation_id_var.get()

correlation_id_var.set(correlation_id)

import httpx

async def add_correlation_id(request):

    correlation_id = correlation_id_var.get()

    if correlation_id:
        request.headers["X-Correlation-Id"] = correlation_id

client = httpx.AsyncClient(
    event_hooks={
        "request": [add_correlation_id]
    }
)

# # Validation
# response = await client.get(
#     "https://api.example.com/fraud-check"
# )

# ### Extension C — Prometheus + Grafana Dashboard *(Advanced)*
# - Export your running `/metrics` to a free [Grafana Cloud](https://grafana.com/products/cloud/) account using the Prometheus remote-write endpoint
# - Build a dashboard with 4 panels: request rate, p99 latency, error rate, circuit breaker trip count

# Create Counter:
CIRCUIT_BREAKER_TRIPS = Counter(
    "circuit_breaker_trips_total",
    "Number of breaker openings"
)

# Increment when breaker opens:
def state_change(self, cb, old, new):

    if str(new) == "open":
        CIRCUIT_BREAKER_TRIPS.inc()

def state_change(self, cb, old, new):

    if str(new) == "open":
        CIRCUIT_BREAKER_TRIPS.inc()

# ### Extension D — Structured Log Aggregation *(Advanced)*
# - Set up a free [Elastic Cloud](https://www.elastic.co/cloud/) cluster or use the Colab local filesystem
# - Configure `structlog` to write logs as newline-delimited JSON to a file
# - Write a query that finds all requests with `latency_ms > 200` for a specific `correlation_id`

import logging

logging.basicConfig(
    filename="payments.log",
    level=logging.INFO
)

# Configure Structlog
structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
    ]
)

# Query Slow Requests
import json

with open("payments.log") as f:  # Validate once payments.log file is created

    for line in f:

        record = json.loads(line)

        if (
            record.get("latency_ms", 0) > 200
            and record.get("correlation_id")
                == "abc123"
        ):
            print(record)