# -*- coding: utf-8 -*-
"""Normalisation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuvXhp8Sl5U-8Er336q4aSnd3eVMSO9H
"""

import pandas as pd
import sqlite3

# Create an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

print("Setup complete. Environment ready.")

# -------------------------------
# UNNORMALIZED DATA (0NF)
# -------------------------------
data_0nf = {
    "Student_ID": [101, 101, 102, 103, 104],
    "Student_Name": ["Alice", "Alice", "Bob", "Charlie", "David"],
    "Course_Code": ["CS101", "MATH201", "CS101", "CS102", "MATH201"],
    "Course_Name": ["Intro to CS", "Calculus I", "Intro to CS", "Data Structures", "Calculus I"],
    "Instructor_ID": ["INS_01", "INS_02", "INS_01", "INS_03", "INS_02"],
    "Instructor_Name": ["Dr. Smith", "Dr. Jones", "Dr. Smith", "Dr. Alan", "Dr. Jones"],
    "Instructor_Office": ["Room 401", "Room 502", "Room 401", "Room 401", "Room 502"],
    "Textbooks_Required": [
        "Python Basics, Intro to CLI",
        "Calculus Vol 1",
        "Python Basics, Intro to CLI",
        "Algorithms Vol 1",
        "Calculus Vol 1"
    ],
    "Grade": ["A", "B", "A", "B+", "A-"]
}

df_0nf = pd.DataFrame(data_0nf)

print("\n--- Unnormalized Data (0NF) ---")
display(df_0nf)

# Flattering the textbooks_required column to ensure atomocity

df_1nf = df_0nf.assign(Textbooks_Required = df_0nf['Textbooks_Required'].str.split(',')).explode('Textbooks_Required')

#Save_To_Sql
df_1nf.to_sql("Table_1NF", conn, index=False, if_exists='replace')
print("----1NF Data (Atomic values enforced)----")
print(f"Row count increased from {len(df_0nf)} to {len(df_1nf)} due to flattering")
df_1nf

"""Student Activity"""

# RUN THIS CELL TO SETUP THE CHALLENGE DATA

import pandas as pd
import sqlite3

conn_challenge = sqlite3.connect(':memory:')

challenge_data = {
    "Visit_ID": [5001, 5001, 5002, 5003],
    "Student_ID": [101, 101, 102, 104],
    "Student_Name": ["Alice", "Alice", "Bob", "David"],
    "Doctor_ID": ["DOC_XYZ", "DOC_XYZ", "DOC_ABC", "DOC_XYZ"],
    "Doctor_Name": ["Dr. Evans", "Dr. Evans", "Dr. Green", "Dr. Evans"],
    "Doctor_Clinic": ["General Medicine", "General Medicine", "Sports Med", "General Medicine"],
    "Prescriptions": ["Amoxicillin, Ibuprofen", "Amoxicillin, Ibuprofen", "Bandages", "Vitamin D"]
}

df_challenge = pd.DataFrame(challenge_data)

df_challenge.to_sql('Patient_Visits_ONF', conn_challenge, index=False, if_exists='replace')

print("--- Challenge Dataset (ONF) ---")

df_challenge

"""**Task-1 : Identify the Flaws**
1. Why does this table violate 1NF ? Which column is the culprit?
    *-- This table violates 1NF as Prescriptions column has a list of elements*
2. Assume Visit_ID is the primary key for a flat version of this table. Why do Student_Name and Doctor_Clinic violate 2NF and 3NF?
   * -- 2NF and 3NF works on the principle that non-prime columns should be dependent on primary key(2NF) and should not be dependent on other non-prime keys(3NF). But Student_Name is depend on Student_ID and Doctor_Clinic is dependent on Doctor_ID/Doctor_Name that are non-prime violating 3NF. Neither of the columns are dependent on Visit_ID that is primary violating 2NF.*
3. If the health center implements a rule where knowing the Doctor_ID immediatly tells you the Doctor_Clinic, but Doctor_ID is not a primary key of the registration tab;e, which normal form is violated.
    *-- 3NF is violated in this case, as it rules that any column should not be dependent on non-prime keys.*

Task-2 Fix it with Code
"""

#1NF

# Flattering the textbooks_required column to ensure atomocity

df_c_1nf = df_challenge.assign(Prescriptions = df_challenge['Prescriptions'].str.split(',')).explode('Prescriptions')

#Save_To_Sql
df_c_1nf.to_sql("Table_1NF", conn, index=False, if_exists='replace')
print("----1NF Data (Atomic values enforced)----")
print(f"Row count increased from {len(df_challenge)} to {len(df_c_1nf)} due to flattering")
df_c_1nf