# -*- coding: utf-8 -*-
"""PromptLayer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QuNmxumexrgUVS-t752INtz8Rc6a6p4N
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q promptlayer openai

from google.colab import userdata
import os

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
os.environ["PROMPTLAYER_API_KEY"] = userdata.get("PROMPTLAYER_API_KEY")
os.environ["GROQ_KEY"] = userdata.get("GROQ_KEY")

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install groq

from groq import Groq
import os

# client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
client = Groq(api_key = os.environ["GROQ_KEY"])

def sendMessage():
  response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Give me a coffee shop slogan."}
    ]
)
  return response.choices[0].message.content
responses = []
for i in range(3):
  responses.append(sendMessage())
for response in responses :
  print(response)

print("Groq key prefix:", os.environ["GROQ_KEY"][:10])

"""Trying to call PromptLayer but facing error"""

from promptlayer import PromptLayer
from openai import OpenAI

pl_client = PromptLayer(api_key=os.environ["PROMPTLAYER_API_KEY"])

client = OpenAI(
    api_key = os.environ["GROQ_KEY"],
    base_url = "https://api.groq.com/openai/v1"
)


pl_response = pl_client.run(
    prompt_name = "coffee-shop-prompt",
    provider="Groq",  # exact provider name from PromptLayer
    model="llama-3.3-70b-versatile",
    input_variables= {}
)

request_id = pl_response["request_id"]
print("Request id ", request_id )

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": "Give me a coffee shop slogan."
        }
    ]
)

pl_client.track.score(
    request_id=1,
    score=100,
    score_name="success"
)


print(response.choices[0].message.content)

"""#Extension Tasks"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%capture
# !pip install langchain langchain-core langchain-groq langchain-openai rouge-score

from langchain_core.prompts import (
    PromptTemplate,
    FewShotPromptTemplate
)

from langchain_core.output_parsers import StrOutputParser

from langchain_groq import ChatGroq

from rouge_score import rouge_scorer

import os

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    api_key=os.environ["GROQ_KEY"],
    temperature=0.3
)

"""##Task 1: Earnings Call Summarization

Zero-Shot Prompt
"""

import langchain
print(langchain.__version__)

earnings_generation_prompt = PromptTemplate(
    input_variables=["company", "quarter"],
    template="""
You are a financial analyst.

Generate a realistic earnings call transcript snippet for {company} during {quarter}.

Include:
- Revenue discussion
- Profitability discussion
- Future guidance
- Management commentary

Length: 150-200 words.
"""
)

generation_chain = (
    earnings_generation_prompt
    | llm
    | StrOutputParser()
)

snippet = generation_chain.invoke(
    {
        "company": "Microsoft",
        "quarter": "Q2 FY2025"
    }
)

print(snippet)

"""Few-Shot Earnings Call Generation"""

examples = [
    {
        "company": "Apple",
        "quarter": "Q1 FY2025",
        "snippet": """
Revenue increased 8% year-over-year driven by strong iPhone and Services growth.
Operating margins improved due to cost optimization.
Management expects continued demand in the upcoming quarter.
"""
    },
    {
        "company": "Amazon",
        "quarter": "Q4 FY2024",
        "snippet": """
AWS continued double-digit growth while advertising revenue exceeded expectations.
Profitability improved through operational efficiencies.
Management provided positive guidance for the next quarter.
"""
    }
]
example_prompt = PromptTemplate.from_template(
"""
Company: {company}

Quarter: {quarter}

Transcript:
{snippet}
"""
)

few_shot_prompt = FewShotPromptTemplate(
    examples=examples,
    example_prompt=example_prompt,
    prefix="""
You are a financial analyst.

Generate realistic earnings call snippets following the style of the examples.
""",
    suffix="""
Company: {company}

Quarter: {quarter}

Transcript:
""",
    input_variables=["company", "quarter"]
)
few_shot_chain = (
    few_shot_prompt
    | llm
    | StrOutputParser()
)
result = few_shot_chain.invoke(
    {
        "company": "NVIDIA",
        "quarter": "Q1 FY2026"
    }
)

print(result)

"""Zero-Shot Summarization"""

summary_prompt = PromptTemplate.from_template(
"""
Summarize the following earnings call transcript.

Include:

1. Revenue Performance
2. Profitability
3. Key Drivers
4. Future Outlook

Transcript:

{transcript}

Summary:
"""
)
summary_chain = (
    summary_prompt
    | llm
    | StrOutputParser()
)
summary = summary_chain.invoke(
    {
        "transcript": snippet
    }
)

print(summary)

"""Few-Shot Summarization"""

summary_examples = [
    {
        "transcript": """
Revenue grew 15% due to cloud services.
Margins expanded because of cost efficiencies.
Management expects strong growth next quarter.
""",
        "summary": """
Revenue increased 15% driven by cloud growth.
Margins improved through operational efficiencies.
Management provided positive guidance.
"""
    }
]
summary_example_prompt = PromptTemplate.from_template(
"""
Transcript:
{transcript}

Summary:
{summary}
"""
)
few_shot_summary_prompt = FewShotPromptTemplate(
    examples=summary_examples,
    example_prompt=summary_example_prompt,
    prefix="""
Summarize earnings call transcripts.
""",
    suffix="""
Transcript:
{transcript}

Summary:
""",
    input_variables=["transcript"]
)
few_shot_summary_chain = (
    few_shot_summary_prompt
    | llm
    | StrOutputParser()
)
summary = few_shot_summary_chain.invoke(
    {
        "transcript": snippet
    }
)

print(summary)

"""ROUGE-L Evaluation"""

reference_summary = """
Revenue increased due to cloud adoption.
Margins improved through cost efficiencies.
Management expects continued growth.
"""

generated_summary = summary
scorer = rouge_scorer.RougeScorer(
    ['rougeL'],
    use_stemmer=True
)

scores = scorer.score(
    reference_summary,
    generated_summary
)

print(scores["rougeL"])

"""Generate 3 Earnings Call Snippets + Summaries + ROUGE-L Together"""

companies = [
    ("Microsoft", "Q2 FY2025"),
    ("NVIDIA", "Q1 FY2026"),
    ("Amazon", "Q4 FY2025")
]

for company, quarter in companies:

    transcript = generation_chain.invoke(
        {
            "company": company,
            "quarter": quarter
        }
    )

    summary = summary_chain.invoke(
        {
            "transcript": transcript
        }
    )

    print("=" * 80)
    print(company)
    print("=" * 80)

    print("\nTRANSCRIPT\n")
    print(transcript)

    print("\nSUMMARY\n")
    print(summary)

"""##TASK 2 - Ticket Classifier

Few-Shot Examples
"""

ticket_examples = [
    {
        "ticket": "I was charged twice this month.",
        "category": "Billing"
    },
    {
        "ticket": "The application crashes when I login.",
        "category": "Technical"
    },
    {
        "ticket": "I cancelled my plan and need my money back.",
        "category": "Refund"
    },
    {
        "ticket": "Can you explain premium features?",
        "category": "General"
    },
    {
        "ticket": "Support has not resolved my issue after multiple attempts.",
        "category": "Escalate"
    }
]

ticket_example_prompt = PromptTemplate.from_template(
"""
Ticket:
{ticket}

Category:
{category}
"""
)

"""Few Shot Classification"""

ticket_prompt = FewShotPromptTemplate(
    examples=ticket_examples,
    example_prompt=ticket_example_prompt,
    prefix="""
You are a support ticket classifier.

Available categories:

- Billing
- Technical
- Refund
- General
- Escalate

Reason step-by-step internally and return only:

Category: <label>
""",
    suffix="""
Ticket:
{ticket}

Category:
""",
    input_variables=["ticket"]
)

"""Chain"""

ticket_chain = (
    ticket_prompt
    | llm
    | StrOutputParser()
)

"""Test"""

ticket = """
I have contacted support three times.
The issue remains unresolved and I need urgent attention.
"""

result = ticket_chain.invoke(
    {
        "ticket": ticket
    }
)

print(result)

"""#Provided by Rajat"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install langchain langchain-community langchain-openai faiss-cpu pypdf

import os

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_KEY")


from langchain_openai import ChatOpenAI
from langchain_community.embeddings import HuggingFaceEmbeddings

from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough


def create_policy_qa_chain(pdf_path: str):

    # Load PDF
    loader = PyPDFLoader(pdf_path)
    docs = loader.load()

    # Split into chunks
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    chunks = splitter.split_documents(docs)

    # Embeddings
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    # Vector Store
    vectorstore = FAISS.from_documents(
        chunks,
        embeddings
    )

    retriever = vectorstore.as_retriever(
        search_kwargs={"k": 3}
    )

    # Groq LLM
    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0
    )

    prompt = ChatPromptTemplate.from_template(
        """
You are an assistant for question-answering tasks.

Use only the provided context.

If the answer is not available in the context,
say "I don't know".

Context:
{context}

Question:
{question}
"""
    )

    def format_docs(docs):
        return "\n\n".join(
            doc.page_content for doc in docs
        )

    rag_chain = (
        {
            "context": retriever | format_docs,
            "question": RunnablePassthrough()
        }
        | prompt
        | llm
        | StrOutputParser()
    )

    return rag_chain

pdf_file = "/content/Deep_TimeSeries_EDA_Report.pdf"

qa_chain = create_policy_qa_chain(pdf_file)

question = "What is the Descriptive Statistics in document?"

response = qa_chain.invoke(question)

print(response)

print()
print()

question = "What is the document regarding?"

response = qa_chain.invoke(question)

print(response)


print()
print()

question = "What is the total strength?"

response = qa_chain.invoke(question)

print(response)