# -*- coding: utf-8 -*-
"""pymupdf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuT_hOE4i2-lG4Hadhey7vlxWrYED9wM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install pymupdf

import fitz
doc = fitz.open("Day4_coding_Assignment.pdf")
print("PDF is opened")
print("----------------- PDF Details ---------------------")
print(f"Pages: {len(doc)}")
print(f"Title: {doc.metadata['title']}")
print(f"Author: {doc.metadata['author']}")
print("----------------- Metadata ---------------------")
print(doc.metadata)
#-----------------Extract text from every page ---------------------
print("-----------------Extract text from every page ---------------------")
for page_num, page in enumerate(doc, start=1):
  text = page.get_text()
  print(text.strip())
doc.close()
print("----------------- Close Document ---------------------")
print("Document closed successfully")