# -*- coding: utf-8 -*-
"""MlFlow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TblH6-LLMPuHhPAyqupWwZjaeUhxHHh

Install Library
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install mlflow

"""Import Library"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import mlflow
import mlflow.sklearn

# Scikit-learn datasets & model selection
from sklearn.datasets import( load_breast_cancer)
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

#Evaluation matrics - THE CORE OF THIS NOTEBOOK
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    ConfusionMatrixDisplay
)

"""Load and Split Data"""

data = load_breast_cancer()
X, y = data.data, data.target
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"Train: {X_train_c.shape}  Test: {X_test_c.shape}")

"""Configure MLflow tracking URI and experiment"""

mlflow.set_tracking_uri("sqlite:///mlflow.db")

mlflow.set_experiment("breast-cancer-classifier")

"""Manual Log"""



MAX_DEPTH = 4
MIN_SAMPLES = 5
CRITERION = 'gini'

mlflow.end_run()

with mlflow.start_run(run_name="manual-logging") as run :
  mlflow.log_param("max_depth", MAX_DEPTH)
  mlflow.log_param("min_sample_split", MIN_SAMPLES)
  mlflow.log_param("criterion", CRITERION)
  mlflow.log_param("random_state", 42 )

clf = DecisionTreeClassifier(
    max_depth=MAX_DEPTH,
    min_samples_split=MIN_SAMPLES,
    criterion=CRITERION,
    random_state=42
)
clf.fit(X_train_c, y_train_c)
y_pred = clf.predict(X_test_c)

#log Evaluation Matrics
mlflow.log_metric("accuracy", accuracy_score(y_test_c, y_pred))
mlflow.log_metric("precision", precision_score(y_test_c, y_pred))
mlflow.log_metric("recall", recall_score(y_test_c, y_pred))
mlflow.log_metric("f1", f1_score(y_test_c, y_pred))

#Save confusion matrix as a PNG artifact
fig, ax = plt.subplots(figsize=(5, 4))
ConfusionMatrixDisplay.from_predictions(y_test_c, y_pred, ax=ax)
plt.tight_layout()
plt.savefig("confusion_matrix.png")
mlflow.log_artifact("confusion_matrix.png")
plt.close()

mlflow.sklearn.log_model(clf, "decision-tree-model")

print(f"RUN ID:   {run.info.run_id}")
print(f"Accuracy:  {accuracy_score(y_test_c, y_pred):.4f}")

mlflow.sklearn.autolog(
    log_input_examples = True,
    log_model_signatures = True,
    log_models = True
)
mlflow.end_run()
with mlflow.start_run(run_name="autolog-run"):
  clf2 = DecisionTreeClassifier(max_depth=6, random_state=42)
  clf2.fit(X_train_c, y_train_c)
  print("autolog run complete - check the UI for logged param & metrics")

!mlflow ui --backend-store-uri sqlite:///mlflow.db --port 5000 &
print("UI running at: http://localhost:5000")

"""Student Assigment"""

import mlflow, mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

mlflow.set_tracking_uri("sqlite:///quiz.db")
mlflow.set_experiment("quiz-experiment")

data = load_iris()
X, y = data.data, data.target
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=0)

MAX_DEPTH = 5
N_ESTIMATORS = 100

with mlflow.start_run(run_name="quiz-run"):
  #1. Log Params
  mlflow.log_param("max_depth", MAX_DEPTH)
  mlflow.log_param("n_estimators", N_ESTIMATORS)

  model = RandomForestClassifier(
      max_depth = MAX_DEPTH, n_estimators=N_ESTIMATORS, random_state=42
  )
  model.fit(X_tr, y_tr)
  preds = model.predict(X_te)

  #2. Log Metrixs
  mlflow.log_metric("accuracy", accuracy_score(y_te, preds))
  mlflow.log_metric("f1", f1_score(y_te, preds, average='macro'))

  #3. Log and register model
  mlflow.sklearn.log_model(
      model,
      "random-forest-model",
      registered_model_name = "iris-rf-classifier"
  )

  #4. Set Tag
  mlflow.set_tag("team", "data-science")