# -*- coding: utf-8 -*-
"""FAQ-Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5EME6whBlWEyxEV9F3Fj9vFyZhD0iHn

##Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %pip install langchain
# %pip install langchain-community
# %pip install langchain-huggingface
# %pip install langchain-groq
# %pip install faiss-cpu
# %pip install sentence-transformers
# %pip install python-dotenv

import os
from google.colab import userdata

"""##Load HuggingFace Embeddings"""

from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

"""##Create Dataset"""

faqs = [
    "What is FAISS? FAISS is a vector database library developed by Meta.",
    "What is RAG? Retrieval Augmented Generation combines retrieval and LLM generation.",
    "What is LangChain? LangChain helps build LLM applications.",
    "What is Groq? Groq provides ultra-fast inference for LLMs.",
    "What are embeddings? Embeddings convert text into vectors.",
    "What is cosine similarity? It measures similarity between vectors.",
    "What is a vector database? It stores embeddings for semantic search.",
    "What is chunking? Splitting text/documents into smaller pieces.",
    "What is reranking? Improving retrieval quality after search.",
    "What is hallucination? When an LLM generates incorrect information out of context."
]

"""##FAISS"""

from langchain_community.vectorstores import FAISS

vector_store = FAISS.from_texts(
    faqs,
    embedding_model
)

"""##Groq LLM"""

from langchain_groq import ChatGroq

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

"""##Similarity Search Function"""

def similarity_search(query):
    docs = vector_store.similarity_search_with_score(
        query,
        k=2
    )

    return docs

"""##Generation Function"""

def answer_question(query):

    results = similarity_search(query)

    context = "\n".join(
        [doc.page_content for doc, score in results]
    )

    prompt = f"""
You are a FAQ assistant.

Use only the context below.

Context:
{context}

Question:
{query}

Answer:
"""

    response = llm.invoke(prompt)

    return response.content, results

"""##Build CLI Interface"""

while True:

    query = input("\nAsk Question: ")

    if query.lower() == "exit":
        break

    answer, docs = answer_question(query)

    print("\nAnswer:")
    print(answer)

    print("\nRetrieved FAQs:")

    for doc, score in docs:
        print(f"\nScore: {score:.4f}")
        print(doc.page_content)