# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7d8C1TLDBEoqHcwdGgRzZuDsdNitQxU
"""

from transformers import pipeline

# ToDo-1 : Initialise a sentiment-analysis pipeline
#Hint: Classifier = pipeline("sentiment analysis")

classifier = pipeline("sentiment-analysis")
'''
sentiment-analysis is a task identifier defined by the Transformer library.

Sentiment Analysis -- sentiment-analysis
Text Classification -- text-classification
Question Answering -- question-answering
Summarization -- summarization
Translation -- translation
'''

sentences = [
    "The client was very satisfied with the delivery",
    "The project is significantly over budget and behind schedule",
    "The new regulatory framework presents both risks and opportunities.",
    # ToDo 2: Add ONE sentense of your own - make it work-relevant
    "The team collobaration is too good that they solved complex escalation within SLA",
    "The output of this project is average",
    "The output of this project is below average"
]

#ToDo 3: Run the classifier on all sentences and print results
#Expected output format:
#The client was satisfied .... -> Positive (0.9987)

def getSentiment(sentence):
  return classifier(sentence)


for sentence in sentences:
  result = getSentiment(sentence)
  # print(result)
  # break   -- Sample Output [{'label': 'POSITIVE', 'score': 0.9992621541023254}]
  label = result[0]['label']
  score = result[0]['score']
  print(f"({sentence[:50]}....) -> {label} ({score:.4f})")