# -*- coding: utf-8 -*-
"""Numpy and Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qraIHII1ZDha5sioo6boiZqtWeFOpRGq

# Numpy and Pandas

Pandas
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = sns.load_dataset('titanic')
df.head()

df2 = df.copy()

print('Before dropping: ', df.shape)
df_dropped = df.dropna()
print('After dropping: ', df_dropped.shape)

df2['age'] = df2['age'].fillna(df2['age'].mean())
df2['embarked'] = df2['embarked'].fillna(df2['embarked'].mode()[0])

df2 = df2.drop(columns=['deck'])
print('Missing after cleaning')
print(df2.isnull().sum())

output_file = 'titanic_data.xlsx'
df2.to_excel(output_file, index = False )
print(f"Dataset saved to {output_file}")

survivors_young = df2.query('survived == 1 and age < 18')
print(len(survivors_young))

# Find all male passengers who paid a fare above 200 and survived.
# df_male = df2.filter(df2['sex'] == 'male').filter(df2['fare'] > 200).filter(df2['alive'] == 'yes')
df_male = df2.query("sex == 'male' and fare > 200 and alive == 'yes'")
print(df_male)

#Using iloc, extract 100 to 109 rows and the last 3 columns
df2.iloc[100:110, -4:-1]

# pivot table - Like excel

pt = df2.pivot_table(
    values = 'survived',
    index = 'pclass',
    columns = 'sex',
    aggfunc= 'mean'
)

pt

#Group By and Aggregration

survival_stats = (
    df2.groupby(['pclass', 'sex'])['survived']
    .agg(['mean', 'count'])
    .rename(columns = {'mean': 'survival_rate', 'count': 'total_count'})
    .sort_values(by='survival_rate', ascending=False)
)

survival_stats

# Multiple Aggregations on different columns at once

class_summery = df2.groupby('pclass').agg(
    avg_age = ('age', 'mean'),
    avg_fare = ('fare', 'mean'),
    survived = ('survived', 'count'),
    n = ('survived', 'sum')  # Sum will encorporate 0
)
class_summery

# Using groupBy find :
#Average fare paid by passengers from each embarkation port
# df2.head()
average_fare = (
    df2.groupby(['embarked'])['fare']
    .agg(['mean'])
    .rename(columns = {'mean' : 'Average Fare'})
)
average_fare

#The number of survivors per class sorted from highest to lowest
no_of_survivors = (
    df2.groupby(['pclass'])['survived']
    .agg(['sum'])
    .rename(columns={'sum' : 'Survivers Count'})
    .sort_values(by='Survivers Count', ascending=False)
)
no_of_survivors

#Merging DataFrames

#Look up tables

class_info = pd.DataFrame({
    'pclass': [1,2,3],
    'class_name' : ['First', 'Second', 'Third']
})

class_info

#Create a second lookup table with port full names

port_info = pd.DataFrame({
    'embarked' : ['C', 'Q', 'S'],
    'port_name' : ['Cherbourg', 'Queenstown', 'Southampton']
})
port_info

#C - Cherbourg, Q - Queenstown, S - Southampton
#Merge it with df2 on 'embarked' and confirm the join worked

df2 = pd.merge(df2, port_info, on = 'embarked', how = 'left')
df2.head() # Validation

# Feature Engineering : age group

df2['age_group'] = pd.cut(
    df2['age'],
    bins = [0, 18, 50, 100],
    labels = ['Child', 'Adult', 'Senior']
)

df2['age_group'].unique()