# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147wUyEH1hh4t0xPsCmNImUE8GlgHKPEP

Importing Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# Importing Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline
plt.rcParams['figure.dpi'] = 110
sns.set_theme(style='whitegrid')
print('Libraries Loaded')

"""Load & Inspect"""

df = sns.load_dataset('taxis')
df.head()  # Verified if dataset is loaded

#Print Shape
print(df.shape)

# Show first rows
df.head()

# Structural info
df.info()
'''
As per the info provided below are the columns with null values.
Total Entries = 6433
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
13  dropoff_borough  6388 non-null   object
'''

# Numeric Summery
df.describe()

"""Clean & Prepare"""

df2 = df.copy() # Copying the dataframe to keep original records

#Applying Transformations on Copied df

df2['payment'] = df2['payment'].fillna(df2['payment'].mode()[0])

df2['pickup_zone'] = df2['pickup_zone'].fillna(df2['pickup_zone'].mode()[0])

df2['pickup_borough'] = df2['pickup_borough'].fillna(df2['pickup_borough'].mode()[0])

df2['dropoff_zone'] = df2['dropoff_zone'].fillna(df2['dropoff_zone'].mode()[0])

df2['dropoff_borough'] = df2['dropoff_borough'].fillna(df2['dropoff_borough'].mode()[0])

# Transforming DataTime into Date format for better statistics

df2['pickup'] = df2['pickup'].dt.strftime('%d-%m-%Y')

df2['dropoff'] = df2['dropoff'].dt.strftime('%d-%m-%Y')

'''
We have used mode as three columns were non integers, usage of other methods are not advisable.
'''

#Verification Post Clean
df2.info()
print(df2.isnull().sum())  # Validating Null Count

# Test Field to understand the data of the table

df2.head()

"""Statistics"""

# Total amount paid based on payment mode

payment_stats = (
    df2.groupby(['payment']).agg({
        'total': 'sum'
    }).reset_index()
)

payment_stats.columns = ['Payment Mode', 'Total Amount Paid']
payment_stats

# Total number of passengers for Each Day

passenger_stats = (
    df2.groupby(['pickup']).agg({
        'passengers' : 'sum'
    }).reset_index()
)
passenger_stats.columns = ['Travel Date', 'No of Passengers']
passenger_stats

# Average Tip and Fare per day

average_tip_fare = (
    df2.groupby(['pickup']).agg({
        'tip' : 'mean',
        'fare' : 'mean'
    }).reset_index()
)
average_tip_fare.columns = ['Travel Date', 'Average Tip', 'Average Fare']
average_tip_fare['Average Tip'] = average_tip_fare['Average Tip'].round(2)
average_tip_fare['Average Fare'] = average_tip_fare['Average Fare'].round(2)
average_tip_fare

"""#Visualize"""

# Normal Bar Graph

fig, ax = plt.subplots(figsize = (6,4))

payment_bars = ax.bar(payment_stats['Payment Mode'], payment_stats['Total Amount Paid'], color = ['tab:blue', 'tab:orange'])
for bar, val in zip(payment_bars, payment_stats['Total Amount Paid']) :
  ax.text(bar.get_x()+bar.get_width()/2, bar.get_height() + 0.01, f"{val: .0}", ha='center', va='bottom', fontsize = 11, fontweight = 'bold')
ax.set_title('Payment Mode Preference of Passengers')
ax.set_yscale('log')
plt.show()

# Scatter Plot

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize = (6,4))
plt.scatter(
    average_tip_fare['Average Fare'],
    average_tip_fare['Average Tip']
)
plt.title('Average Fare vs Average Tip')
plt.show()

fig, ax = plt.subplots(figsize = (14,6))
# passenger_stats.columns = ['Travel Date', 'No of Passengers']
passenger_bars = ax.bar(passenger_stats['Travel Date'], passenger_stats['No of Passengers'])
ax.set_title('Number of passengers per day')
plt.xticks(rotation = 45)  # Since Days were overlapping so titled the title to avoid overlap in x-axis
plt.tight_layout()
plt.show()

#Histogram

sns.histplot(df2['fare'], bins = 30 )
plt.title('Fare Distribution Histogram')
plt.xlabel('Fare Amount')
plt.ylabel('Frequency')
plt.show()

"""Key Insights

Please find key insights based on above graphs

1.   Payment Mode Preference of Passengers : Checking the bar graph it is quite clear that users prefer to use credit card rather than cash to pay.
2.   Average Fare vs Average Tip: Scatter graph suggests the dependecy on average fare and average tip. Tip added by customers is quite low when taxi fare is less. Meanwhile as price increases, drastic increase in tip can be observed. Later point tip decreases gradually stating that customer has set a fixed amount and they don't prefer to pay more tip if fare is at highest.


1.   Number of passengers per day: Bar graph is repeated as bar graph is the best plot to show the overall count. Observing the graph we can conclude that everyday atleast 200+ people travel using taxi.
2.   Fare Distribution Histogram: Histogram provides insights that the max taxi fare is set to 60. Considering so we can predict that if we are booking a taxi, the fare of taxi would be between 0-20.

Narrative Conclusion

Instead of looping through tables or datasets everytime we require any statistics, plotting related data with relevant graph could reduce the effort of iterating through numbers. Graphs are not only visually attractive but also quite helpful to conclude multiple insights that would require multistep mathematical and statistical calculations.
"""