# -*- coding: utf-8 -*-
"""GAN Image Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Jna_FRcxQwYRRhGqb_XQwZ0KPDfSYyl

Import Libraries
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

"""Generator Block"""

class Generator(nn.Module):
  def __init__(self, z_dim):
    super().__init__()
    self.model = nn.Sequential(
        nn.ConvTranspose2d(z_dim, 256, 7, 1, 0), # Input 1x1, Output 7x7
        nn.BatchNorm2d(256),
        nn.ReLU(),
        nn.ConvTranspose2d(256, 128, 4, 2, 1), # Input 7x7, Output 14x14
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.ConvTranspose2d(128, 1, 4, 2, 1), # Input 14x14, Output 28x28
        nn.Tanh(),
    )
  def forward(self, x):
      return self.model(x)

"""Discriminator Block"""

class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Conv2d(1, 64, 4, 2, 1),
        nn.LeakyReLU(0.2),
        nn.Conv2d(64, 128, 4, 2, 1),
        nn.BatchNorm2d(128),
        nn.LeakyReLU(0.2),
        nn.Flatten(),
        nn.Linear(128*7*7, 1),
        nn.Sigmoid(),
    )

  def forward(self, x):
      return self.model(x)

device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""Hyperparameters"""

batch_size = 128
lr = 0.002
z_dim = 100
epochs = 10

"""Dataset Loading"""

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

"""Initializing loss function, generator, discriminator and optimizers"""

criterion = nn.BCELoss()
generator = Generator(z_dim).to(device)
discriminator = Discriminator().to(device)
optimizer_g = optim.Adam(generator.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_d = optim.Adam(discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

def show_images(fake):
  img = fake.detach().cpu()[:16]
  grid = img.view(16, 28, 28)

  fig, axes = plt.subplots(4, 4, figsize=(5, 5))
  for i, ax in enumerate(axes.flatten()):
    ax.imshow(grid[i], cmap='gray')
    ax.axis('off')
  plt.show()

"""Training Step"""

for epoch in range(epochs):
  for real, _ in dataloader:
    real = real.to(device)
    batch_size = real.size(0)

    # Training discriminator
    noise = torch.randn(batch_size, z_dim, 1, 1).to(device)
    fake = generator(noise)

    real_labels = torch.ones(batch_size, 1).to(device)
    # Label Smoothing
    real_labels = torch.ones(batch_size, 1).to(device) * 0.9

    fake_labels = torch.zeros(batch_size, 1).to(device)

    # Real Loss
    D_real = discriminator(real)
    loss_real = criterion(D_real, real_labels)

    # Fake Loss
    D_fake = discriminator(fake.detach())
    loss_fake = criterion(D_fake, fake_labels)

    # Total Loss
    loss_D = loss_real + loss_fake

    optimizer_d.zero_grad()
    loss_D.backward()
    optimizer_d.step()

    # Train Discriminator
    output = discriminator(fake)
    g_loss = criterion(output, real_labels) # wants Discriminator to think fake is real

    optimizer_g.zero_grad()
    g_loss.backward()
    optimizer_g.step()
  show_images(real)
  show_images(fake)
  print(f"Epoch [{epoch}/{epochs}], Loss D: {loss_D.item()}, Loss G: {g_loss.item()}")

"""Extention task

Higher Resolution Dataset (64×64)
"""

highres_transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

highres_dataset = datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=highres_transform
)

highres_loader = DataLoader(
    highres_dataset,
    batch_size=128,
    shuffle=True
)

print("64x64 Dataset Loaded Successfully")

"""Higher Resolution Generator Block"""

class Generator64(nn.Module):
    def __init__(self, z_dim):
        super().__init__()

        self.model = nn.Sequential(

            # 1x1 -> 4x4
            nn.ConvTranspose2d(z_dim, 512, 4, 1, 0, bias=False),
            nn.BatchNorm2d(512),
            nn.ReLU(True),

            # 4x4 -> 8x8
            nn.ConvTranspose2d(512, 256, 4, 2, 1, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(True),

            # 8x8 -> 16x16
            nn.ConvTranspose2d(256, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(True),

            # 16x16 -> 32x32
            nn.ConvTranspose2d(128, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            # 32x32 -> 64x64
            nn.ConvTranspose2d(64, 1, 4, 2, 1, bias=False),

            nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)

"""Higher Resolution Discriminator Block"""

class Discriminator64(nn.Module):
    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(

            # 64x64 -> 32x32
            nn.Conv2d(1, 64, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            # 32x32 -> 16x16
            nn.Conv2d(64, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),

            # 16x16 -> 8x8
            nn.Conv2d(128, 256, 4, 2, 1, bias=False),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),

            # 8x8 -> 4x4
            nn.Conv2d(256, 512, 4, 2, 1, bias=False),
            nn.BatchNorm2d(512),
            nn.LeakyReLU(0.2, inplace=True),

            # 4x4 -> 1x1
            nn.Conv2d(512, 1, 4, 1, 0, bias=False),

            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x).view(-1, 1)

"""Initialize New Model"""

generator64 = Generator64(z_dim).to(device)
discriminator64 = Discriminator64().to(device)

criterion64 = nn.BCELoss()

optimizer_g64 = optim.Adam(
    generator64.parameters(),
    lr=0.0002,
    betas=(0.5, 0.999)
)

optimizer_d64 = optim.Adam(
    discriminator64.parameters(),
    lr=0.0002,
    betas=(0.5, 0.999)
)

print(generator64)
print(discriminator64)

"""Visualization"""

def show_images_64(fake):

    img = fake.detach().cpu()[:16]

    fig, axes = plt.subplots(
        4,
        4,
        figsize=(8, 8)
    )

    for i, ax in enumerate(axes.flatten()):
        ax.imshow(
            img[i].squeeze(),
            cmap='gray'
        )
        ax.axis('off')

    plt.tight_layout()
    plt.show()

"""Training High Resolution Dataset"""

epochs64 = 10

for epoch in range(epochs64):

    for real, _ in highres_loader:

        real = real.to(device)

        batch_size = real.size(0)

        # -------------------
        # Train Discriminator
        # -------------------

        noise = torch.randn(
            batch_size,
            z_dim,
            1,
            1,
            device=device
        )

        fake = generator64(noise)

        real_labels = torch.ones(
            batch_size,
            1,
            device=device
        ) * 0.9

        fake_labels = torch.zeros(
            batch_size,
            1,
            device=device
        )

        d_real = discriminator64(real)
        loss_real = criterion64(
            d_real,
            real_labels
        )

        d_fake = discriminator64(
            fake.detach()
        )

        loss_fake = criterion64(
            d_fake,
            fake_labels
        )

        d_loss = loss_real + loss_fake

        optimizer_d64.zero_grad()
        d_loss.backward()
        optimizer_d64.step()

        # -------------------
        # Train Generator
        # -------------------

        output = discriminator64(fake)

        g_loss = criterion64(
            output,
            real_labels
        )

        optimizer_g64.zero_grad()
        g_loss.backward()
        optimizer_g64.step()

    print(
        f"Epoch [{epoch+1}/{epochs64}] "
        f"D Loss: {d_loss.item():.4f} "
        f"G Loss: {g_loss.item():.4f}"
    )

    show_images_64(fake)

"""Generate Final Image"""

generator64.eval()

with torch.no_grad():

    noise = torch.randn(
        16,
        z_dim,
        1,
        1,
        device=device
    )

    generated_images = generator64(noise)

show_images_64(generated_images)

# To Check if Colab is connected to GPU for faster excution
import torch

print("CUDA Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("Running on CPU")

"""Steps to change to GPU

*   Change Runtime → Change runtime type → GPU
*   Reconnect
*   Rerun all cells
"""