# -*- coding: utf-8 -*-
"""SQL_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fB4BkwINysfNK8o8piD9MuXs8I1D0TxA
"""

import sqlite3
conn = sqlite3.connect("shopey.db")
cursor = conn.cursor()
print("Connected Successfully")

cursor.executescript("""

DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS vendors;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE vendors (
    vendor_id INTEGER PRIMARY KEY AUTOINCREMENT,
    vendor_name VARCHAR(150) NOT NULL,
    contact_email VARCHAR(255)
);

CREATE TABLE products (
    product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name VARCHAR(200) NOT NULL,
    category_id INTEGER,
    vendor_id INTEGER,
    unit_price NUMERIC(10,2) NOT NULL,
    stock_qty INTEGER DEFAULT 0
);

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'Pending'
);

CREATE TABLE order_lines (
    line_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL
);

CREATE TABLE payments (
    payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER UNIQUE NOT NULL,
    payment_date TIMESTAMP,
    method VARCHAR(50),
    amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'Pending'
);

""")

conn.commit()

cursor.executescript(
    """
-- Customers
INSERT INTO customers (first_name, last_name, email, phone)
VALUES
('John', 'Doe', 'john.doe@gmail.com', '9876543210'),
('Jane', 'Smith', 'jane.smith@gmail.com', '9876543211'),
('Michael', 'Brown', 'michael.brown@gmail.com', '9876543212'),
('Emily', 'Davis', 'emily.davis@gmail.com', '9876543213'),
('David', 'Wilson', 'david.wilson@gmail.com', '9876543214');

-- Categories
INSERT INTO categories (category_name, description)
VALUES
('Electronics', 'Electronic gadgets and accessories'),
('Clothing', 'Men and Women clothing'),
('Books', 'Educational and fiction books'),
('Home Appliances', 'Home and kitchen appliances'),
('Sports', 'Sports and fitness products');

-- Vendors
INSERT INTO vendors (vendor_name, contact_email)
VALUES
('Tech World', 'sales@techworld.com'),
('Fashion Hub', 'contact@fashionhub.com'),
('Book Store', 'info@bookstore.com'),
('Home Needs', 'support@homeneeds.com'),
('Sport Zone', 'help@sportzone.com');

-- Products
INSERT INTO products
(product_name, category_id, vendor_id, unit_price, stock_qty)
VALUES
('Laptop', 1, 1, 65000.00, 20),
('Smartphone', 1, 1, 30000.00, 50),
('T-Shirt', 2, 2, 799.00, 100),
('Jeans', 2, 2, 1499.00, 75),
('Python Programming Book', 3, 3, 599.00, 40),
('Microwave Oven', 4, 4, 8500.00, 15),
('Refrigerator', 4, 4, 28000.00, 10),
('Cricket Bat', 5, 5, 2500.00, 25),
('Football', 5, 5, 1200.00, 30),
('Data Science Book', 3, 3, 899.00, 35);

-- Orders
INSERT INTO orders (customer_id, order_date, status)
VALUES
(1, '2026-05-01 10:00:00', 'Completed'),
(2, '2026-05-02 11:15:00', 'Completed'),
(3, '2026-05-03 14:30:00', 'Pending'),
(1, '2026-05-05 09:45:00', 'Shipped'),
(4, '2026-05-06 16:20:00', 'Completed');

-- Order Lines
INSERT INTO order_lines
(order_id, product_id, quantity, unit_price)
VALUES
(1, 1, 1, 65000.00),
(1, 5, 2, 599.00),
(2, 2, 1, 30000.00),
(2, 3, 3, 799.00),
(3, 8, 1, 2500.00),
(4, 6, 1, 8500.00),
(4, 9, 2, 1200.00),
(5, 10, 1, 899.00),
(5, 4, 2, 1499.00);

-- Payments
INSERT INTO payments
(order_id, payment_date, method, amount, status)
VALUES
(1, '2026-05-01 10:15:00', 'Credit Card', 66198.00, 'Completed'),
(2, '2026-05-02 11:30:00', 'UPI', 32397.00, 'Completed'),
(3, NULL, 'UPI', 2500.00, 'Pending'),
(4, '2026-05-05 10:00:00', 'Debit Card', 10900.00, 'Completed'),
(5, '2026-05-06 16:35:00', 'Net Banking', 3897.00, 'Completed');
    """
)
conn.commit()

cursor.execute("SELECT * FROM customers")
print(cursor.fetchone())

cursor.execute(
    """
select
c.first_name || ' ' || c.last_name as customer_name,
COUNT(distinct o.order_id) as total_orders ,
SUM(ol.quantity*ol.unit_price) as total_spent,
 RANK() OVER (ORDER BY SUM(ol.quantity * ol.unit_price) DESC) AS customer_rank
 from customers c
 join Orders o on c.customer_id = o.customer_id
 join order_lines  ol on o.order_id = ol.order_id
group by  c.customer_id,
    c.first_name,
    c.last_name
ORDER BY customer_rank;
    """
)
conn.commit()
print(cursor.fetchall())